--DROPPING REDUNDANT TABLES

DROP TABLE IF EXISTS ATTENDENCE;
DROP TABLE IF EXISTS CLASSVENUE;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS STUDENT;

--DEFINING SCHEMA

CREATE TABLE STUDENT
(
	ROLLNUM VARCHAR(40),
	NAME_ VARCHAR(40) NOT NULL,
	GENDER VARCHAR(40) NOT NULL,
	PHONENUMBER VARCHAR(40)
);

CREATE TABLE TEACHER
(
	ID INT,
	NAME_ VARCHAR(40),
	DESIGNATION VARCHAR(40) NOT NULL,
	DEPARTMENT VARCHAR(40) NOT NULL
);

CREATE TABLE CLASSVENUE
(
	ID_ INT,
	BUILDING VARCHAR(40) NOT NULL,
	ROOMNUM INT NOT NULL,
	TEACHER_NAME VARCHAR(40) NOT NULL,
	TEACHER_ID INT NOT NULL
);

CREATE TABLE ATTENDENCE
(
	ROLLNUM VARCHAR(40),
	DATE_ DATE NOT NULL,
	STATUS_ VARCHAR(1) NOT NULL,
	CLASSVENUE INT NOT NULL
);


--HARDCODE/INSERTED VALUES THROUGH INSERT FUNCTION

INSERT INTO STUDENT
VALUES ('L191162', 'ABDULLAH NAZIR', 'MALE', '0333-3333333');
INSERT INTO STUDENT
VALUES ('L194124', 'RAFIA AHMED', 'FEMALE', '0333-3456789');
INSERT INTO STUDENT
VALUES ('L194125', 'BASIT JUNAID', 'MALE', '0345-3243567');

INSERT INTO TEACHER
VALUES (1, 'RAIDA MUNIR', 'LAB INSTRUCTOR', 'COMPUTER SCI.');
INSERT INTO TEACHER
VALUES (2, 'HARIS BIN REHAN', 'LECTURER', 'CIVIL ENGG.');
INSERT INTO TEACHER
VALUES (3, 'SANA FATIMA', 'PROFESSOR', 'ELECTICAL ENGG.');

INSERT INTO CLASSVENUE
VALUES (1, 'COMPUTER SCI.', 2, 'HARIS BIN REHAN', 2);
INSERT INTO CLASSVENUE
VALUES (2, 'CIVIL', 7, 'RAIDA MUNIR', 1);

INSERT INTO ATTENDENCE
VALUES ('L191162', '2023-02-22', 'P', 2);
INSERT INTO ATTENDENCE
VALUES ('L194124', '2023-02-23', 'A', 1);
INSERT INTO ATTENDENCE
VALUES ('L194125', '2023-03-04', 'P', 2);
