--ADDING PK CONTRAINTS

ALTER TABLE STUDENT
ADD CONSTRAINT PK_constraint_student
PRIMARY KEY (ROLLNUM);

ALTER TABLE TEACHER
ADD CONSTRAINT PK_constraint_teacher
PRIMARY KEY (ID, NAME_);

ALTER TABLE ATTENDENCE
ADD CONSTRAINT PK_constraint_attendence
PRIMARY KEY (ROLLNUM);

ALTER TABLE CLASSVENUE
ADD CONSTRAINT PK_constraint_classvenue
PRIMARY KEY (ID_);

