--ADDING FK CONTRAINTS

ALTER TABLE CLASSVENUE
ADD CONSTRAINT FK_constraint_classvenue
FOREIGN KEY (TEACHER_ID, TEACHER_NAME)
REFERENCES TEACHER (ID, NAME_);


ALTER TABLE ATTENDENCE
ADD CONSTRAINT FK_constraint_attendence
FOREIGN KEY (CLASSVENUE)
REFERENCES CLASSVENUE (ID_);