--ADDING BASIC CHECKS AND CONSTRAINTS

ALTER TABLE TEACHER
ADD CONSTRAINT unique_name_constraint
UNIQUE (NAME_);

ALTER TABLE STUDENT
ADD CONSTRAINT gender_check_constraint
CHECK (STUDENT.GENDER='MALE' OR STUDENT.GENDER='FEMALE');

ALTER TABLE ATTENDENCE
ADD CONSTRAINT attendence_check_constraint
CHECK (ATTENDENCE.STATUS_='P' OR ATTENDENCE.STATUS_='A');