--TESTING QUERIES

-- VALID QUERY BUT LOGICAL ERROR SINCE THE 'WARNING_COUNT' IS 'FLOAT' AND STORED IN 'INT' 
INSERT INTO STUDENT
VALUES ('L192334', 'SHAHID IQBAL', 'MALE', 3.2);

-- INVALID QUERY BECAUSE, ID --> 4 IS NOT DEFINED IN TEACHER TABLE
-- IT CAN CORRECTED BY INSERTING A TEACHER WITH ID --> 4 AND NAME --> 'ALI' 
INSERT INTO CLASSVENUE
VALUES (3, 'CS', 5, 'ALI', 4);

-- COMPLETELY VALID QUERIES
UPDATE TEACHER
SET NAME_='DR. SANA FATIMA'
WHERE NAME_='SANA FATIMA';

DELETE FROM STUDENT
WHERE ROLLNUM = 'L192334';

DELETE FROM STUDENT
WHERE ROLLNUM = 'L194125';

DELETE FROM ATTENDENCE
WHERE ROLLNUM = 'L194124' AND STATUS_='A';
