DROP DATABASE IF EXISTS ahmeddb;
CREATE DATABASE ahmeddb;
USE ahmeddb;

-- Create the TEAM table
DROP TABLE IF EXISTS TEAM;
CREATE TABLE TEAM (
  TEAMNUM INT PRIMARY KEY,
  TEAMNAME VARCHAR(255) NOT NULL,
  CITY VARCHAR(255) NOT NULL,
  MANAGER VARCHAR(255)
);

-- Create the PLAYER table
DROP TABLE IF EXISTS PLAYER;
CREATE TABLE PLAYER (
  PLAYERNUM INT PRIMARY KEY,
  PLAYERNAME VARCHAR(255) NOT NULL,
  AGE INT
);


-- Create the COACH table
DROP TABLE IF EXISTS COACH;
CREATE TABLE COACH (
  TEAMNUM INT,
  COACHNAME VARCHAR(255) PRIMARY KEY,
  FOREIGN KEY (TEAMNUM) REFERENCES TEAM(TEAMNUM)
);

-- Create the WORK EXPERIENCE table
DROP TABLE IF EXISTS WORK_EXPERIENCE;
CREATE TABLE WORK_EXPERIENCE (
  TEAMNUM INT,
  COACHNAME VARCHAR(255) NOT NULL,
  EXPERIENCETYPE VARCHAR(255) NOT NULL,
  YEARSEXPERIENCE INT,
  FOREIGN KEY (TEAMNUM, COACHNAME) REFERENCES COACH(TEAMNUM, COACHNAME)
);

-- Create the BATS table
DROP TABLE IF EXISTS BATS;
CREATE TABLE BATS (
  TEAMNUM INT,
  SERIALNUM VARCHAR(255) PRIMARY KEY,
  MANUFACTURER VARCHAR(255) NOT NULL,
  FOREIGN KEY (TEAMNUM) REFERENCES TEAM(TEAMNUM)
);

-- Create the AFFILIATION table
DROP TABLE IF EXISTS AFFILIATION;
CREATE TABLE AFFILIATION (
  PLAYERNUM INT,
  TEAMNUM INT,
  YEARS INT,
  BATTINGAVG DECIMAL(5,2),
  FOREIGN KEY (PLAYERNUM) REFERENCES PLAYER(PLAYERNUM),
  FOREIGN KEY (TEAMNUM) REFERENCES TEAM(TEAMNUM)
);

