-- 1
SELECT TEAMNAME, CITY
FROM TEAM
WHERE TEAM.TEAMNUM>15
ORDER BY TEAMNAME;

-- 2
SELECT PLAYERNAME
FROM PLAYER
WHERE AGE<18;

-- 3
SELECT *
FROM WORK_EXPERIENCE
WHERE YEARSEXPERIENCE BETWEEN 5 AND 10
AND EXPERIENCETYPE='College Coach'
AND COACHNAME LIKE '% R%';


-- 4
SELECT SUM(YEARSEXPERIENCE)
FROM WORK_EXPERIENCE
WHERE COACHNAME='Coach Waqar' AND TEAMNUM=25;

-- 5
SELECT COUNT(DISTINCT(EXPERIENCETYPE))
FROM WORK_EXPERIENCE
WHERE COACHNAME='Coach Waqar' AND TEAMNUM=3;

-- 6
SELECT SUM(YEARSEXPERIENCE), COACHNAME
FROM WORK_EXPERIENCE
WHERE TEAMNUM=3
GROUP BY COACHNAME;

-- 7
SELECT COUNT(DISTINCT(MANUFACTURER)) 
FROM BATS;

-- 8
SELECT PLAYERNAME
FROM PLAYER 
JOIN AFFILIATION
ON PLAYER.PLAYERNUM = AFFILIATION.PLAYERNUM
JOIN TEAM
ON AFFILIATION.TEAMNUM = TEAM.TEAMNUM
WHERE TEAMNAME='Yankees' AND YEARS>=5;


-- 9
SELECT SUM(YEARSEXPERIENCE), COACHNAME
FROM TEAM
JOIN WORK_EXPERIENCE
ON TEAM.TEAMNUM = WORK_EXPERIENCE.TEAMNUM
WHERE TEAMNAME='Royals'
GROUP BY COACHNAME
HAVING SUM(YEARSEXPERIENCE)>8;

-- 10
SELECT PLAYERNAME
FROM PLAYER
ORDER BY AGE
LIMIT 3;

-- 11
SELECT PLAYERNAME
FROM PLAYER
WHERE PLAYERNAME LIKE '% M%'
ORDER BY AGE
LIMIT 3;


-- 12
SELECT PLAYERNAME
FROM AFFILIATION 
JOIN PLAYER
ON AFFILIATION.PLAYERNUM = PLAYER.PLAYERNUM
GROUP BY AFFILIATION.PLAYERNUM
HAVING COUNT(*) > 2;

-- 13
SELECT PLAYERNAME
FROM PLAYER 
JOIN AFFILIATION
ON AFFILIATION.PLAYERNUM = PLAYER.PLAYERNUM
WHERE AFFILIATION.PLAYERNUM = NULL;

-- 14
SELECT PLAYERNAME, COUNT(DISTINCT(TEAMNUM))
FROM AFFILIATION 
JOIN PLAYER
ON AFFILIATION.PLAYERNUM = PLAYER.PLAYERNUM
GROUP BY AFFILIATION.PLAYERNUM;

-- 15
SELECT TEAMNAME, AVG(BATTINGAVG)
FROM AFFILIATION 
JOIN TEAM
ON AFFILIATION.TEAMNUM = TEAM.TEAMNUM
GROUP BY TEAMNAME;



